version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123

  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
